"""Generate the data module used by the Netlify Function from Python course content."""
import json
from pathlib import Path

from content import LEVELS, SCHEMA

course = []
for level in LEVELS:
    tasks = []
    for task in level["tasks"]:
        meta = task[7] if len(task) > 7 else {}
        tasks.append({
            "title": task[0], "prompt": task[1], "solution": task[2],
            "hint1": task[3], "hint2": task[4], "explanation": task[6],
            "mode": meta.get("mode", "read"), "target": meta.get("target"),
            "required": meta.get("required"),
        })
    course.append({
        "title": level["title"], "topic": level["topic"],
        "theory": level["theory"], "example": level["example"],
        "required": level.get("required"), "tasks": tasks,
    })

output = Path(__file__).parent / "netlify" / "lib" / "course-data.mjs"
output.write_text(
    "// Generated by export_course.py; edit content.py/curriculum_extra.py instead.\n"
    + "export const COURSE = " + json.dumps(course, ensure_ascii=False, separators=(",", ":")) + ";\n"
    + "export const SCHEMA_SQL = " + json.dumps(SCHEMA, ensure_ascii=False) + ";\n",
    encoding="utf-8",
)
print(f"Exported {len(course)} levels and {sum(len(x['tasks']) for x in course)} tasks")
